# Assignment 2

## Numpy

### Import Library

In [1]:
import numpy as np

### Solve Questions

1) Write a NumPy program to test whether none of the elements of a given array is zero.

In [2]:
no_zero = np.array([1, 2, 3, 4])
no_zero2 = np.array([1, 2, 3, 4, 0])

test1 = np.all(no_zero != 0)
test2 = np.all(no_zero2 != 0)

print(test1)
print(test2)

True
False


____________

2) Write a NumPy program to test whether any of the elements of a given array is non-zero.  

In [3]:
arr = np.array([0, 0, 0, 3])
arr2 = np.array([0, 0, 0, 0])


any_non_zero = np.any(arr != 0)
any_non_zero2 = np.any(arr2 != 0)

print("Any of the elements are non-zero:", any_non_zero)
print("Any of the elements are non-zero:", any_non_zero2)

Any of the elements are non-zero: True
Any of the elements are non-zero: False


___________

3) Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two 
given  

In [4]:
arr1 = np.array([1.0, 2.0, 3.0, 4.4])
arr2 = np.array([1.0, 2.5, 3.1, 4.4])

equal_arr = np.equal(arr1, arr2)
tolerance_arr = np.isclose(arr1, arr2, atol=0.1)

print("Element-wise comparison (equal):")
print(equal_arr)

print("\nElement-wise comparison (equal within a tolerance):")
print(tolerance_arr)

Element-wise comparison (equal):
[ True False False  True]

Element-wise comparison (equal within a tolerance):
[ True False  True  True]


____________

4) Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [5]:
ten_zeros = np.zeros(10)
ten_ones  = np.ones(10)
ten_fives = np.full(10, 5)

print("Array of 10 zeros:", ten_zeros)
print("Array of 10 ones:", ten_ones)
print("Array of 10 fives:", ten_fives)

Array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of 10 ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of 10 fives: [5 5 5 5 5 5 5 5 5 5]


___________

5) Write a NumPy program to create an array of the integers from 30 to 70

In [6]:
arr = np.arange(30, 71)
print("Array of integers from 30 to 70:", arr)

Array of integers from 30 to 70: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


__________

6) Write a NumPy program to create a 3x3 identity matrix  

In [7]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


________

7) Write a NumPy program to generate a random number between 0 and 1

In [12]:
random_number = np.random.rand()
print(random_number)


0.011125582687197433


_______

8) Write a NumPy program to generate an array of 15 random numbers from a standard normal 
distribution  

In [15]:
random_numbers = np.random.randn(15)
print(random_numbers)

[-0.18570074  0.40263923  0.35561418  0.05975718  1.19933946  1.00624608
  1.40280497 -0.78358836 -0.02065339 -0.57961429  1.31589238  0.65110084
  0.9053334   0.07317691  1.80782386]


_____

9) Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values 
except the first and last.   

In [17]:
vector_renge = np.arange(15, 56)
print(vector_renge[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


_____________________

10) Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10  

In [18]:
random_vector = np.random.randint(0, 11, size=5)
print(random_vector)

[10  3  1  0  5]


_________

11) Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal 
to 1, and inside 0.  

In [19]:
matrix = np.zeros((10, 10))

matrix[0, :] = 1        
matrix[-1, :] = 1       
matrix[:, 0] = 1        
matrix[:, -1] = 1       

print(matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


______________

12) Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 
3, 4, 5.  

In [20]:
zero_matrix = np.zeros((5, 5))

np.fill_diagonal(zero_matrix, [1, 2, 3, 4, 5])

print(zero_matrix)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


___________

13) Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main 
diagonal

In [22]:
matrix = np.ones((4, 4))

np.fill_diagonal(matrix, 0)

matrix[1::2, ::2] = 0  
matrix[::2, 1::2] = 0

print(matrix)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


______

14) Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) 
and load it.   

In [23]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

np.savez_compressed('arrays.npz', array1=array1, array2=array2)

loaded_data = np.load('arrays.npz')

loaded_array1 = loaded_data['array1']
loaded_array2 = loaded_data['array2']

print("Loaded Array 1:", loaded_array1)
print("Loaded Array 2:", loaded_array2)

Loaded Array 1: [1 2 3 4 5]
Loaded Array 2: [ 6  7  8  9 10]


__________

15)  Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values. 
Select 


In [25]:
random_array = np.random.rand(40)
random_array

array([0.1442899 , 0.45489213, 0.6946307 , 0.0272231 , 0.68241551,
       0.57275992, 0.71753735, 0.56372329, 0.17262513, 0.69594454,
       0.91331483, 0.52685222, 0.4439991 , 0.24932743, 0.388372  ,
       0.62044485, 0.39085959, 0.13705681, 0.21156129, 0.85129954,
       0.07870186, 0.59960471, 0.48948398, 0.30922832, 0.67421429,
       0.35565857, 0.38652851, 0.90789407, 0.34767013, 0.74236252,
       0.76779351, 0.46050526, 0.59098082, 0.22006396, 0.01768681,
       0.99032993, 0.23293003, 0.23128682, 0.47506683, 0.233006  ])

__________

16) Write a NumPy program to extract all numbers from a given array which are less and greater than a 
specified number

In [26]:
array = np.array([10, 25, 5, 30, 15, 2, 20, 40, 35, 0])

specified_number = 15

less_than = array[array < specified_number]

greater_than = array[array > specified_number]


print("Original array:", array)
print(f"Numbers less than {specified_number}:", less_than)
print(f"Numbers greater than {specified_number}:", greater_than)

Original array: [10 25  5 30 15  2 20 40 35  0]
Numbers less than 15: [10  5  2  0]
Numbers greater than 15: [25 30 20 40 35]
